### ISSUE TITLE
tests under python 2.7

### ISSUE THREAD

**Issue by jeremygray** [aroberge/easygui_qt#11]
Automated tests would make it much easier to support both python 2.7 and 3.4, e.g., using https://travis-ci.org

I tried to get tests to run using `python -m unittest discover` from the command line, but had multiple issues.

1. Fixed PIL not being able to import Image by:

    % sudo mkdir -p /opt/anaconda1anaconda2anaconda3/lib/
    % sudo ln /Users/jgray/anaconda/lib/libtiff.5.dylib /opt/anaconda1anaconda2anaconda3/lib/libtiff.5.dylib

2. See branch `p2-tests-work-in-progress` for tweaks needed to `test_easygui_qt.py` for it to be able to even run. These are just notes to share, not something to merge in this form.

3. The windows that come up are always behind other windows for me, and I have to manually bring them to the foreground in order for pyautogui to be able to send key-presses, etc. (This is a problem for me during normal usage, not just tests.)

4. And then tests still fail with AssertionErrors

**Comment by aroberge** [comment]
I have asked on the PyQt mailing list and on stackoverflow and no one has been able to help me.  Since it looks like it just will not happen, I am going to close this issue and update the docs to indicate that unit tests are unfortunately not performed.
