### ISSUE TITLE
get_date returns string instead of datetime.date

### ISSUE THREAD

**Issue by uvchik** [aroberge/easygui_qt#25]
In the documentation it says that the output of the CalendarWidget would be a datetime.date object.

![bildschirmfoto - 28 11 2016 - 20 51 42](https://cloud.githubusercontent.com/assets/4760584/20683505/833a3810-b5ac-11e6-8981-1e339efd90f7.png)

This would be great for further processing but I get a string.

```python
>>> date = easy.get_date("Select a date.")
>>> print(type(date))
<class 'str'>
```

Is it possible to return a datetime.date instance because a string is difficult to handle.

**Comment by aroberge** [comment]
I just ran the code from the repo:

    C:\Users\Andre\Desktop\GitHub\easygui_qt>python
    Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import easygui_qt as easy
    >>> d = easy.get_date()
    >>> d
    datetime.date(2016, 11, 21)

The output is a datetype object.

What version are you using?

**Comment by aroberge** [comment]
I just noticed that the version on pypi is 0.9.1 ... and that it does not incorporate the change to a datetime object.

**Comment by aroberge** [comment]
The version on pypi has been updated to reflect the documentation. Closing this issue.

**Comment by uvchik** [comment]
Sorry for not posting the version I use and thank you for updating the package. 

Everything works fine now. Nice package!
